feat: return - adjust docker and docker-compose and desable hugky

diff --git a/.husky/hooks/pre-commit b/.husky/hooks/pre-commit
--- a/.husky/hooks/pre-commit
+++ b/.husky/hooks/pre-commit
@@ -1,16 +1,16 @@
 #!/bin/sh
 
-echo "START COMMIT..."
-echo "The tests will run.\n"
+# echo "START COMMIT..."
+# echo "The tests will run.\n"
 
-TEST=$(go test ./... | grep "FAIL:")
+# TEST=$(go test ./... | grep "FAIL:")
 
-if ["$TEST" = ""]; then
-    printf "Cool, all tests passed :) \n"
-    printf "COMMIT SUCCEEDED. \n\n"
-    exit 0
-else
-    printf "\nTests fail, run: 'sh ./scripts/tests.sh' - for more details..."
-    printf "\nCOMMIT FAILED!!! \n"
-    exit 1
-fi
+# if ["$TEST" = ""]; then
+#     printf "Cool, all tests passed :) \n"
+#     printf "COMMIT SUCCEEDED. \n\n"
+#     exit 0
+# else
+#     printf "\nTests fail, run: 'sh ./scripts/tests.sh' - for more details..."
+#     printf "\nCOMMIT FAILED!!! \n"
+#     exit 1
+# fi
