++ first test with husky ruuning test before commit

diff --git a/.husky/hooks/pre-commit b/.husky/hooks/pre-commit
--- a/.husky/hooks/pre-commit
+++ b/.husky/hooks/pre-commit
@@ -1,7 +1,15 @@
 #!/bin/sh
 
-echo "Start commit! \n"
+echo "START COMMIT... \n"
+echo "The tests will run.\n"
 
-sh "./scripts/tests.sh"
+TEST=$(go test ./... | grep "FAIL:")
 
-echo "\nEnd commit! \n"
+if ["$TEST" = ""]; then
+    printf "COMMIT SUCCEEDED. \n"
+    exit 0
+else
+    printf "\nTests fail, RUN: 'sh ./scripts/tests.sh' - for run the tests... \n"
+    printf "\nCOMMIT FAILED!!! \n"
+    exit 1
+fi
